<AdminScreen>:
    md_bg_color: app.bg_color

    MDBoxLayout:
        orientation: "vertical"
        MDTopAppBar:
            title: "NEXA ADMIN   |   Gestão"
            left_action_items: [["arrow-left", lambda x: app.go_home()]]
            right_action_items: [["theme-light-dark", lambda x: app.toggle_theme()]]
            md_bg_color: app.surface_color
            specific_text_color: 1, 0.90, 1, 1
        MDBoxLayout:
            orientation: "vertical"
            padding: dp(22)
            spacing: dp(14)
            NexaTitle:
                text: "Administração"
            NexaCard:
                orientation: "vertical"
                size_hint_y: None
                height: dp(270)
                MDLabel:
                    text: "USUÁRIOS E PERFIS"
                    bold: True
                    theme_text_color: "Custom"
                    text_color: app.text_color
                MDLabel:
                    text: "Administradores  •  2"
                    theme_text_color: "Custom"
                    text_color: app.muted_color
                MDLabel:
                    text: "Recepção  •  4"
                    theme_text_color: "Custom"
                    text_color: app.muted_color
                MDLabel:
                    text: "Faturamento  •  2"
                    theme_text_color: "Custom"
                    text_color: app.muted_color
                MDLabel:
                    text: "Clínico  •  6"
                    theme_text_color: "Custom"
                    text_color: app.muted_color
                MDLabel:
                    text: "Auditoria: ativa"
                    theme_text_color: "Custom"
                    text_color: 0.60, 0.95, 0.78, 1
                NexaButton:
                    text: "ATUALIZAR CONFIGURAÇÕES"
                    on_release: root.save_status()
