#:import dp kivy.metrics.dp

<NexaCard@MDCard>:
    radius: [dp(18), dp(18), dp(18), dp(18)]
    elevation: 0
    padding: dp(18)
    md_bg_color: app.card_color
    line_color: 0.55, 0.20, 0.85, 0.30
    line_width: dp(1)

<NexaTitle@MDLabel>:
    bold: True
    font_size: "24sp"
    theme_text_color: "Custom"
    text_color: app.text_color

<NexaSection@MDLabel>:
    bold: True
    font_size: "16sp"
    theme_text_color: "Custom"
    text_color: 0.58, 0.24, 0.85, 1

<NexaButton@MDRaisedButton>:
    md_bg_color: 0.42, 0.16, 0.95, 1
    text_color: 1, 1, 1, 1
    radius: [dp(12), dp(12), dp(12), dp(12)]
    elevation: 2

<NexaChip@MDFlatButton>:
    theme_text_color: "Custom"
    text_color: 0.95, 0.82, 1, 1
