name: Build NEXA Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-apk:
    name: Build NEXA APK
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Build NEXA com Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: .
          buildozer_version: stable
          command: buildozer -v android debug

      - name: Publicar APK
        uses: actions/upload-artifact@v4
        with:
          name: nexa-apk
          path: ${{ steps.buildozer.outputs.filename }}
          if-no-files-found: error
          retention-days: 14
